### ISSUE TITLE
Fab bootstrap_from_checkout fails when downgrading setuptools on OSX

### ISSUE THREAD

**Issue by n0izn0iz** [assembl/assembl#125]
Log: https://pastebin.com/C9W7YBLh

Seems to be a setuptools bug https://github.com/pypa/setuptools/issues/1086

I've managed to get past this error by downgrading setuptools to 36.1.1 in the virtualenv before rerunning bootstrap_from_checkout

**Comment by maparent** [comment]
The solution here is probably upgrading the setuptools version in requirements.txt. Do you mind trying that?

**Comment by n0izn0iz** [comment]
On it

**Comment by vincentfretin** [comment]
If it helps, nowadays you can create a virtualenv with the --no-setuptools option, so you can avoid issues when downgrading setuptools after in requirements.txt

**Comment by n0izn0iz** [comment]
Bumping setuptools to 36.2.0 in requirements works!
