### ISSUE TITLE
Fab bootstrap_from_checkout fails on system_db_user when env.postgres_db_user is undefined on OSX

### ISSUE THREAD

**Issue by n0izn0iz** [assembl/assembl#126]
Log: https://pastebin.com/7WnGBM1X

I think that I managed to get past it by changing
```
def system_db_user():
    if env.postgres_db_user:
        return env.postgres_db_user
    if env.mac:
        # Brew uses user
        return getuser()
    return "postgres"  # linux postgres
```
to
```
def system_db_user():
    if env.mac:
        # Brew uses user
        return getuser()
    if env.postgres_db_user:
        return env.postgres_db_user
    return "postgres"  # linux postgres
```
but not sure since fab didn't complain that the user didn't exist the second time

**Comment by maparent** [comment]
Ah! we would want to give priority to the env, in case it's an external postgres; but it makes sense that env.postgres_db_user should be undefined on mac-develop.
And indeed, the mac.rc file undefines that key. But the error was that fab did not expect that key to be undefined. Solved in 078698ec2e7a5d241ad779dc6b322fa6ce40ce2c
