### ISSUE TITLE
OSX libxml2 is not compatible with lxml in venv

### ISSUE THREAD

**Issue by n0izn0iz** [assembl/assembl#128]
During the installation process at this step:
`assembl-add-user --email your_email@email.com --name "Your Name" --username desiredusername --password yourpassword local.ini`

I get: `ImportError: lxml.etree does not export expected C function adoptExternalDocument`

This question seems to be linked the problem: https://stackoverflow.com/questions/13355984/get-errors-when-import-lxml-etree-to-python
```
$> otool -L venv/lib/python2.7/site-packages/lxml/etree.so
venv/lib/python2.7/site-packages/lxml/etree.so:
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.51.1)
```
`nm /usr/lib/libxml2.2.dylib | grep adoptExternalDocument` returns nothing

**Comment by maparent** [comment]
Returns something on my OSX. What version of OSX are you using?

**Comment by n0izn0iz** [comment]
10.12.5

**Comment by n0izn0iz** [comment]
`export DYLD_LIBRARY_PATH=/usr/local/lib`
seems to help but I get other errors so not sure

**Comment by maparent** [comment]
That will create other errors. Please let's discuss this over hangouts.

**Comment by maparent** [comment]
Ah, issue already solved; just not on master yet.

**Comment by sejames** [comment]
I was seeing this error in my venv (Centos 6 and 7) using Python 2.7.13 SCL and Python 2.7.5 base

Fixes were found in
[Python-saml #30](https://github.com/onelogin/python-saml/issues/30)
[Python-Saml #177](https://github.com/onelogin/python-saml/issues/177)
