### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by kamiljaszczynski** [assembl/assembl#144]
There is a some way to add new language?
I found folder contains language files. But one of them is binary file. 
I need some tools to compile some file to binary ? 
How can i turn on another language ?
Only from db ?
I didn't find answer in documentation.

Thanks for help.

**Comment by vincentfretin** [comment]
There is a locale folder containing the po files. The mo files are binary generated from the po files.
There are two fabric tasks
`fab -c configs/local.rc build_po_files`
to extract messages from the code, generate the pot and sync the po files

and
`fab -c configs/local.rc build_translation_json_files`
to generate mo files and json files.

If you want to add a new language, just write another po file and edit the translations with poedit.

**Comment by swergas** [comment]
Documentation about translation is here: https://dev-assembl.bluenove.com/static/techdocs/localization.html

It probably needs an update now that we have 2 versions of the frontend :)

**Comment by swergas** [comment]
Would you like us to add a new language on transifex so that you can contribute translations?

**Comment by kamiljaszczynski** [comment]
I want add polish version.

I found folder with locale. I see there de, en, fr, es. But in assembla on
web site i see only fr and en.

Thanks for replay :>

**Comment by vincentfretin** [comment]
on the right of the debate title, you have a small arrow, click on it then go to Discsussion settings and then Discussion preferences

**Comment by kamiljaszczynski** [comment]
OK i found.
Thanks!

Is there some way to remove discussion ? Or  i need remove id from db ?

**Comment by maparent** [comment]
You can delete it in pshell, but not through the UI.
As superuser, you may be able to delete it with a RESTful DELETE commande on the /data/Discussion/[id] api point.

**Comment by kamiljaszczynski** [comment]
Thanks :>
