### ISSUE TITLE
Control of expansion state of table of ideas

### ISSUE THREAD

**Issue by jmatsushita** [assembl/assembl#21]
I remember you mentioned the TOI's state would be remembered per user. Maybe also that a particular TOI expansion state could be part of a deep link. Is that something you're looking into?

**Comment by swergas** [comment]
We started recently to work on this :)

**Comment by swergas** [comment]
As of today, here are the features we have:
* Everyone can toggle the expansion state of each idea of the table of ideas (expanded = shows children) 
* When a logged in user toggles the expansion state of an idea, this state gets saved on the user account. When the user closes the window and comes back as logged, he sees the same state. When he logs in from another machine, he also sees the same state.
* A cog menu at the top-right of the table of ideas enables to expand or collapse all ideas
* An admin can save the current expanded/collapsed state of his table of ideas to set it as default for all other users. Logged in users who expand/collapse an idea override this default for this idea (for their account)

![capture du 2017-02-15 11-21-12](https://cloud.githubusercontent.com/assets/733425/22970089/1d02c2f8-f371-11e6-9648-568d5f5d6c96.png)


So the feature you are talking about is now supported, and yes, a potential next step could be to generate a deep link for users to share specific states of the table of ideas :)
