### ISSUE TITLE
Error when adding a new discussion

### ISSUE THREAD

**Issue by dachary** [assembl/assembl#31]
After adding a new discussion 

![assembl2](https://cloud.githubusercontent.com/assets/433594/15161317/f96b68a4-16fd-11e6-9998-6fcaf84aa3dd.png)

an error shows

![assembl3](https://cloud.githubusercontent.com/assets/433594/15161337/182edc30-16fe-11e6-988c-006983d09478.png)

This can be reproduce consistently at http://citizen99.org/regles-constituante

**Comment by swergas** [comment]
Thanks, I have been able to reproduce the bug several times on this discussion. Citizen99 was running an older version of Assembl (last update was from a bit before 2016-03-05). I have just updated it and now I can't reproduce the bug anymore.

**Comment by swergas** [comment]
Here is a screenshot of the precise error I had (this one is on another discussion of the same server, but for the same API method called: marking a message as read)

![capture du 2016-05-12 12 16 02](https://cloud.githubusercontent.com/assets/733425/15241408/035717e8-18f0-11e6-9066-50ba4be0f74d.png)
